#!/usr/bin/env python3
"""generate_canon.py — Phase 5 canon generators (spec §12.5).

One definition per thing: these surfaces are RENDERED from canon and must
never be hand-edited. CI regenerates and diffs (generated-matches-source).

    python3 tools/generate_canon.py manifest        # core/manifest.yaml
    python3 tools/generate_canon.py souls           # generated/hermes/profiles/<agent>/SOUL.md
    python3 tools/generate_canon.py entity-claude   # generated/entity-claude/<brain>/CLAUDE.md
    python3 tools/generate_canon.py commands        # generated/claude/commands/... thin adapters
    python3 tools/generate_canon.py all

Sources: core/skills/*/skill.yaml, core/agent-templates/*,
brains/<x>/BRAIN.md, config/hermes-profiles.yaml.
Output is deterministic (sorted, no timestamps) so CI diffs are stable.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("FAIL: PyYAML required (pip install pyyaml)")
    sys.exit(1)

REPO = Path(__file__).resolve().parent.parent
MARKER = "<!-- Generated by tools/generate_canon.py — DO NOT HAND-EDIT. Edit the sources: {src} -->"


def load_skills() -> dict[str, dict]:
    skills = {}
    for d in sorted((REPO / "core" / "skills").iterdir()):
        y = d / "skill.yaml"
        if d.is_dir() and y.exists():
            skills[d.name] = yaml.safe_load(y.read_text())
    return skills


def gen_manifest() -> None:
    skills = load_skills()
    domains = sorted({s.get("domain", "?") for s in skills.values()})
    lines = [
        "# core/manifest.yaml — index of core skills.",
        "# GENERATED by tools/generate_canon.py — DO NOT HAND-EDIT (spec §2).",
        "# Regenerate: python3 tools/generate_canon.py manifest",
        "version: 1",
        f"suites: [{', '.join(domains)}]",
        "",
        "skills:",
    ]
    width = max(len(sid) for sid in skills) + 1
    for sid, s in sorted(skills.items()):
        adapter = (s.get("merged_from") or ["(none)"])[0]
        lines.append(
            f"  {sid + ':':<{width}} "
            f"{{domain: {s.get('domain', '?')}, maturity: {s.get('maturity', '?')}, adapter: {adapter}}}"
        )
    (REPO / "core" / "manifest.yaml").write_text("\n".join(lines) + "\n")
    print(f"manifest: {len(skills)} skills")


def strip_template_header(text: str) -> str:
    """Drop the template's own H1 + '<!-- Template source ... -->' comment."""
    lines = text.splitlines()
    out, skipping = [], False
    for ln in lines:
        if ln.startswith("# ") and "template" in ln.lower() or ln.startswith("# SOUL.base.md") or ln.startswith("# CLAUDE.md — {"):
            continue
        if "<!-- Template source" in ln:
            skipping = True
        if skipping:
            if "-->" in ln:
                skipping = False
            continue
        out.append(ln)
    return "\n".join(out).lstrip("\n")


def fill(template: str, mapping: dict[str, str]) -> str:
    out = strip_template_header(template)
    for k, v in mapping.items():
        out = out.replace("{" + k + "}", v)
    return out


def gen_souls() -> None:
    reg = yaml.safe_load((REPO / "config" / "hermes-profiles.yaml").read_text())
    base = (REPO / "core" / "agent-templates" / "SOUL.base.md").read_text()
    # strip the template's own comment block (first <!-- ... -->)
    for agent, a in sorted((reg.get("agents") or {}).items()):
        if a.get("live_status") != "production":
            continue
        brain = a["brain"]
        brain_md = (REPO / "brains" / brain / "BRAIN.md").read_text()
        body = fill(base, {
            "DISPLAY_NAME": a.get("display_name", agent),
            "HERMES_PROFILE": a.get("hermes_profile", agent),
            "BRAIN": brain,
            "AGENT": agent,
            "OPERATING_BRANCH": str(reg.get("operating_branch", "main")),
            "WORKDIR": a.get("workdir", "(unset)"),
        })
        binding = [
            "\n## Runtime binding (from config/hermes-profiles.yaml)\n",
            f"- role: {a.get('role')}",
            f"- workdir: {a.get('workdir')}",
            f"- owns_crons: {a.get('owns_crons', False)}",
            f"- mcp_servers: {a.get('mcp_servers', [])}",
            f"- credential_scope: {a.get('credential_scope', [])}",
        ]
        if a.get("must_not_hold"):
            binding.append(f"- must_not_hold (negative scope, checklist-tested): {a['must_not_hold']}")
        if a.get("routes_to"):
            binding.append(f"- routes_to: {a['routes_to']}")
        marker = MARKER.format(src=f"core/agent-templates/SOUL.base.md + brains/{brain}/BRAIN.md + config/hermes-profiles.yaml")
        out = "\n".join([marker, "", f"# {a.get('display_name', agent)} — SOUL (`{a.get('hermes_profile')}`)", "", body.strip(), "", *binding, "",
                         f"## Persona and entity context (brains/{brain}/BRAIN.md)", "", brain_md.strip(), ""])
        dest = REPO / "generated" / "hermes" / "profiles" / agent / "SOUL.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(out)
        print(f"soul: {agent} ({a.get('hermes_profile')})")


def gen_entity_claude() -> None:
    template = (REPO / "core" / "agent-templates" / "entity-claude.template.md").read_text()
    for b in sorted((REPO / "brains").iterdir()):
        bm = b / "BRAIN.md"
        if not (b.is_dir() and bm.exists()):
            continue
        body = bm.read_text().strip()
        title_line = body.splitlines()[0].lstrip("# ").strip()
        marker = MARKER.format(src=f"core/agent-templates/entity-claude.template.md + brains/{b.name}/BRAIN.md")
        out = marker + f"\n\n# CLAUDE.md — {title_line}\n\n" + fill(template, {
            "ENTITY_TITLE": title_line,
            "BRAIN": b.name,
            "BRAIN_MD_BODY": body,
        })
        dest = REPO / "generated" / "entity-claude" / b.name / "CLAUDE.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(out)
        print(f"entity-claude: {b.name}")


def gen_commands() -> None:
    skills = load_skills()
    prefix = ".claude/commands/"
    for sid, s in sorted(skills.items()):
        adapter = (s.get("merged_from") or [""])[0]
        if not adapter.startswith(prefix):
            print(f"skip {sid}: adapter path not under {prefix} ({adapter})")
            continue
        rel = adapter[len(prefix):]
        desc = (s.get("description") or sid).strip()
        inputs = s.get("inputs") or []
        marker = MARKER.format(src=f"core/skills/{sid}/ (SKILL.md + skill.yaml)")
        lines = [
            "---",
            f"description: {desc}",
            "---",
            marker,
            "",
            f"# {sid} (generated adapter)",
            "",
            f"Canon: **`core/skills/{sid}/SKILL.md`** — read it fully before acting;",
            "it is the complete procedure. This adapter only routes you there.",
            "",
            "1. Resolve `{brain}`: the entity in context → its `path` in `WORKSPACE.yaml`",
            "   (e.g. `brains/mitl`). Ask if ambiguous.",
            f"2. Read `core/skills/{sid}/SKILL.md` (and its `references/` if present).",
            "3. Execute with `{brain}` substituted throughout. Honor every checkpoint,",
            "   quality gate, and guardrail in the canon.",
        ]
        if inputs:
            lines += ["", "Expected inputs: " + ", ".join(str(i) for i in inputs)]
        dest = REPO / "generated" / "claude" / "commands" / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text("\n".join(lines) + "\n")
    print(f"commands: {len(skills)} adapters -> generated/claude/commands/")


def gen_install() -> None:
    """Install generated command adapters into .claude/commands/ (the live
    executable surface). Rich hand adapters were retired to archive/ on
    2026-07-03; from then on .claude/commands copies of core skills are
    generated files — CI regenerates + installs and fails on drift."""
    src_root = REPO / "generated" / "claude" / "commands"
    n = 0
    for f in sorted(src_root.rglob("*.md")):
        rel = f.relative_to(src_root)
        dest = REPO / ".claude" / "commands" / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(f.read_text())
        n += 1
    print(f"install: {n} adapters -> .claude/commands/")


def main() -> int:
    ap = argparse.ArgumentParser(description="Render canon-derived surfaces")
    ap.add_argument("surface", choices=["manifest", "souls", "entity-claude", "commands", "install", "all"])
    args = ap.parse_args()
    if args.surface in ("manifest", "all"):
        gen_manifest()
    if args.surface in ("souls", "all"):
        gen_souls()
    if args.surface in ("entity-claude", "all"):
        gen_entity_claude()
    if args.surface in ("commands", "all"):
        gen_commands()
    if args.surface in ("install", "all"):
        gen_install()
    return 0


if __name__ == "__main__":
    sys.exit(main())
